### ISSUE TITLE
Move debug mode into config

### ISSUE THREAD

**Issue by mattgarner** [eastgenomics/trendyQC#133]

**Comment by Yu-jinKim** [comment]
Right now the debug variable for Django is hardcoded in `settings.py`. In order to provide more flexibility, it has been decided to move the debug variable to the docker-compose file to define debug at runtime.
To do so:
- Remove the hardcoded-ness of the variable in `settings.py`
- Add debug to the docker-compose file
- Add reference to that new debug environment variable in `readme.md`

**Comment by Yu-jinKim** [comment]
Fixed in #135
